apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  namespace: sonarqube
data:
  SONAR_JDBC_URL: "jdbc:postgresql://sonarqube-postgres:5432/sonarqube"
  SONAR_JDBC_USERNAME: "sonar"
  POSTGRES_DB: "sonarqube"