apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{APP_NAME}}-hpa
  namespace: {{NAMESPACE}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{APP_NAME}}
  minReplicas: {{HPA_MIN_REPLICAS}}
  maxReplicas: {{HPA_MAX_REPLICAS}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{CPU_UTILIZATION}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{MEMORY_UTILIZATION}}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: {{HPA_SCALEUP_PERCENT}}
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: {{HPA_SCALEDOWN_PERCENT}}
          periodSeconds: 60