apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  selector:
    app: {{APP_LABEL}}
  ports:
    - protocol: TCP
      port: {{SERVICE_PORT}}         
      targetPort: {{CONTAINER_PORT}}
  type: {{SERVICE_TYPE}}