apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins-controller
          image: mennahaggag/nuvvai-jenkins-image:v2
          ports:
           - name: http
             containerPort: 8080
           - name: agent-listener
             containerPort: 50000
           - name: https
             containerPort: 8443
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
              subPath: jenkins-data
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
